# مرحلة البناء
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# نسخ كل شيء من المجلد الحالي إلى داخل الـ Container
COPY . .

# عمل Restore و Publish مباشرة
RUN dotnet publish "lapshop.sln" -c Release -o out

# مرحلة التشغيل
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "lapshop.dll"]